version: '3.9'

services:
  batch_process:
    profiles: ["batch"]
    build:
      context: .
      dockerfile: deploy/Dockerfile_news
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /mnt/g/AINewsletter:/data/results
    secrets:
      - db_server
      - db_name
      - db_user
      - db_password
      - openai_api_key 
      - gpt4_api_key
      - libkey_api_key
      - ncbi_api_key
      - azure_proxy_key
  streamlit_app:
    profiles: ["web"]
    build:
      context: .
      dockerfile: deploy/Dockerfile_web
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    secrets:
      - db_server
      - db_name
      - db_user
      - db_password
      - openai_api_key 
      - gpt4_api_key
      - libkey_api_key
      - ncbi_api_key
secrets:
  db_server:
    file: /mnt/p/Secrets/db_server.txt
  db_name:
    file: /mnt/p/Secrets/db_name.txt
  db_user:
    file: /mnt/p/Secrets/db_user.txt
  db_password:
    file: /mnt/p/Secrets/db_password.txt
  openai_api_key:
    file: /mnt/p/Secrets/openai_api_key.txt
  gpt4_api_key:
    file: /mnt/p/Secrets/gpt4_api_key.txt
  libkey_api_key:
    file: /mnt/p/Secrets/libkey_api_key.txt
  ncbi_api_key:
    file: /mnt/p/Secrets/ncbi_api_key.txt
  azure_proxy_key:
    file: /mnt/p/Secrets/azure_proxy_key.txt

