# app/Dockerfile

FROM python:3.10-slim

WORKDIR /deploy

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    pandoc \
    && rm -rf /var/lib/apt/lists/*

# Copy local repository content instead of cloning
COPY . .

RUN pip3 install -r requirements.txt
RUN pip3 install --user pip setuptools wheel
RUN pip3 install --user -e .

CMD ["python", "./ScopingReview/main.py", "--output", "/data/results"]


