import ScopingReview.prompts as ScopingReview_prompts
import ScopingReview_config.config as ScopingReview_config
import ScopingReview.data as review_data


import openai

from langchain_community.callbacks import get_openai_callback

from langchain.schema import HumanMessage, SystemMessage

def generate_search_string(input_research_q, loop_n=0, last_query=""):
    """
    The `generate_search_string` function takes an input research question, an optional loop number, and
    an optional last query. It generates a search string using OpenAI's ChatGPT model and returns the
    generated search string.
    
    Args:
      input_research_q: The input research question that you want to generate a search string for.
      loop_n: The `loop_n` parameter is used to keep track of the number of times the search query has
    been looped. It is an optional parameter with a default value of 0. Defaults to 0
      last_query: The `last_query` parameter is a string that represents the previous search query that
    was executed. It is used in the `generate_search_string` function to provide context to the AI model
    about the previous search results. This can be helpful when the previous search did not yield many
    results and the user wants
    
    Returns:
      The function `generate_search_string` returns a string that is generated by the OpenAI ChatGPT
    model.
    """
    prompt = ScopingReview_prompts.PUBMED_PROMPT.format(input_research_q)
    chat=ScopingReview_config.PUBMED_CHAT
    if loop_n>0:
        prompt = prompt + ScopingReview_prompts.FEW_RESULTS_PROMPT + last_query
    with get_openai_callback() as response_meta:
        messages = [
            SystemMessage(
                content="You are an expert at conducting medical literature searches. You help beginning researchers."
            ),
            HumanMessage(
                content=prompt
            ),
        ]
        response = chat.invoke(messages)
        
    return response.content, response_meta
  
def generate_overall_introduction(question, abstracts, help_type):
  """
  The function `generate_overall_introduction` takes a question, a list of abstracts, and a help type
  as input, and generates an overall introduction by summarizing the literature related to the
  question.
  
  Args:
    question: The question you want to generate an overall introduction for.
    abstracts: The `abstracts` parameter is a list of abstracts from relevant literature sources.
  These abstracts provide a summary of the research papers or articles related to the given question.
    help_type: The `help_type` parameter is used to specify the type of help you are seeking. It can
  be a string that describes the specific type of assistance you need, such as "clarification",
  "summary", "analysis", or any other relevant description. This helps the AI understand the context
  and provide
  
  Returns:
    The function `generate_overall_introduction` returns the overall introduction generated by the AI
  model.
  """
  prompt = ScopingReview_prompts.SUMMARIZE_LITERATURE_PROMPT.format(question, help_type, abstracts)
  chat=ScopingReview_config.CHAT
  with get_openai_callback() as response_meta:
      messages = [
          SystemMessage(
              content="You are an expert at conducting medical literature searches. You help beginning researchers."
          ),
          HumanMessage(
              content=prompt
          ),
      ]
      response = chat(messages)

  return response.content, response_meta


def categorize(category_df, input_text):
  reduced_df = review_data.get_relevant_rows(category_df)
  cost = 0.0
  input_list = input_text.split(',')
  input_list = [value.strip() for value in input_list if value.strip()]

  for index, row in reduced_df.iterrows():
      data = row['abstract']
      result = ScopingReview_config.CHAT.invoke(ScopingReview_prompts.categorization_chat_prompt.format_prompt(categories=input_list, context=data).to_messages())
      reduced_df.at[index, 'category'] = result.content
  return reduced_df

