import ScopingReview.prompts as ScopingReview_prompts
import ScopingReview_config.config as ScopingReview_config
import ScopingReview_config.boilerplate as ScopingReview_boilerplate
import ScopingReview.data as review_data
import openai
import pandas as pd
from langchain_community.callbacks import get_openai_callback
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain.schema import HumanMessage, SystemMessage

def generate_search_string(input_research_q, loop_n=0, last_query=""):
    """
    The `generate_search_string` function takes an input research question, an optional loop number, and
    an optional last query. It generates a search string using OpenAI's ChatGPT model and returns the
    generated search string.
    
    Args:
      input_research_q: The input research question that you want to generate a search string for.
      loop_n: The `loop_n` parameter is used to keep track of the number of times the search query has
    been looped. It is an optional parameter with a default value of 0. Defaults to 0
      last_query: The `last_query` parameter is a string that represents the previous search query that
    was executed. It is used in the `generate_search_string` function to provide context to the AI model
    about the previous search results. This can be helpful when the previous search did not yield many
    results and the user wants
    
    Returns:
      The function `generate_search_string` returns a string that is generated by the OpenAI ChatGPT
    model.
    """
    prompt = ScopingReview_prompts.PUBMED_PROMPT.format(input_research_q)
    chat=ScopingReview_config.PUBMED_CHAT
    if loop_n>0:
        prompt = prompt + ScopingReview_prompts.FEW_RESULTS_PROMPT + last_query
    with get_openai_callback() as response_meta:
        messages = [
            SystemMessage(
                content="You are an expert at conducting medical literature searches. You help beginning researchers."
            ),
            HumanMessage(
                content=prompt
            ),
        ]
        response = chat.invoke(messages)
        
    return response.content, response_meta
  
def generate_overall_introduction(question, abstracts, help_type):
    """
    The function `generate_overall_introduction` takes a question, a list of abstracts, and a help type
    as input, and generates an overall introduction by summarizing the literature related to the
    question.

    Args:
    question: The question you want to generate an overall introduction for.
    abstracts: The `abstracts` parameter is a list of abstracts from relevant literature sources.
    These abstracts provide a summary of the research papers or articles related to the given question.
    help_type: The `help_type` parameter is used to specify the type of help you are seeking. It can
    be a string that describes the specific type of assistance you need, such as "clarification",
    "summary", "analysis", or any other relevant description. This helps the AI understand the context
    and provide

    Returns:
    The function `generate_overall_introduction` returns the overall introduction generated by the AI
    model.
    """
    prompt = ScopingReview_prompts.SUMMARIZE_LITERATURE_PROMPT.format(question, help_type, abstracts)
    chat=ScopingReview_config.CHAT
    with get_openai_callback() as response_meta:
        messages = [
            SystemMessage(
                content="You are an expert at conducting medical literature searches. You help beginning researchers."
            ),
            HumanMessage(
                content=prompt
            ),
        ]
        response = chat(messages)

    return response.content, response_meta


def categorize(category_df, input_text):
    # TODO: change the category_df to reduced_df --- in all places
    # reduced_df = review_data.get_relevant_rows(category_df)
  cost = 0.0
  input_list = input_text.split(',')
  input_list = [value.strip() for value in input_list if value.strip()]

  for index, row in category_df.iterrows():
      data = row[['abstract', 'title']]
      result = ScopingReview_config.CHAT35.invoke(ScopingReview_prompts.categorization_chat_prompt.format_prompt(categories=input_list, context=data).to_messages())
      keyword_list = result.content.replace("'", "")
      category_df.at[index, 'category'] = keyword_list.lower()
  return category_df

def categories_limit_check(df):
    categories_exceeding_limit = []
    if df is not None:
        
        df['category'] = df['category'].str.split(', ')
        df_exploded = df.explode('category')
            
        unique_values_counts = df_exploded['category'].value_counts()
        # print(unique_values_counts)
        for category, count in unique_values_counts.items():
            if count > ScopingReview_config.SUBCLASS_THRESHOLD:
                categories_exceeding_limit.append(category)
        
    return categories_exceeding_limit

def sub_categorize(original_df, categories_exceeding_limit, sub_categories):
    df_copy = original_df.copy()
    reduced_df = review_data.get_relevant_rows(df_copy)
    # should already be transformed to a python list by categories_limit_check()
    df_exploded = reduced_df.explode('category')

    # Prepare new sub-categories
    sub_categories = [value.strip() for value in sub_categories.split(',') if value.strip()]
    # Replace categories exceeding limit with sub-categories
    for remove_category in categories_exceeding_limit:
        remove_category = remove_category.strip()
        remove_category = remove_category.lower()
        df_exploded['category'] = df_exploded['category'].str.lower()
        mask = df_exploded['category'] == remove_category
        for index, row in df_exploded[mask].iterrows():
            # index is preserved across the explode
            if row.category == remove_category:
                data = row[['abstract', 'title']]
                # Assuming your categorization process is correctly set up
                result = ScopingReview_config.CHAT35.invoke(
                    ScopingReview_prompts.categorization_chat_prompt.format_prompt(
                        categories=sub_categories, context=data
                    ).to_messages()
                )
                category_to_write = result.content.replace("'", "")
                df_exploded.at[index, 'category'] = category_to_write.lower()
                
    unique_values_list = list(df_exploded['category'].unique())
    # Reverse the explode operation to update original dataframe
    df = df_exploded.groupby(df_exploded.index).agg({'category': lambda x: ', '.join(x), 'Relevant': 'first'})

    # Merging other columns back into the df
    df_final = df_copy.drop(columns=['category', 'Relevant']).merge(df, left_index=True, right_index=True, how='right')
    # Categorization
    for index, row in df_final.iterrows():
        data = row[['abstract', 'title']]
        result = ScopingReview_config.CHAT.invoke(ScopingReview_prompts.categorization_chat_prompt.format_prompt(categories=unique_values_list, context=data).to_messages())
        reduced_df.at[index, 'category'] = result.content
    return reduced_df, ''.join(unique_values_list)
    

def summarize_article_in_chunks(article_text):
    # Splitting the article text into manageable chunks
    text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(chunk_size=13000, chunk_overlap=1000)
    texts = text_splitter.create_documents([article_text])

    # Create the initial summary for the first chunk
    summary = ScopingReview_config.FASTER_CHAT.invoke(ScopingReview_prompts.initial_summary_prompt.format(text=texts[0]))

    # Iteratively refine the summary with each subsequent chunk
    for text_chunk in texts[1:]:
        summary = ScopingReview_config.FASTER_CHAT.invoke(ScopingReview_prompts.refine_summary_prompt.format(existing_summary=summary, text=text_chunk))

    return summary
  
def summarize_all_categories(df, user_question):
    # use abtract when text is not available.
    df['Text'] = df.apply(lambda row: row['abstract'] if row['Text'] == 'Text not available' else row['Text'], axis=1)

    # takes in multiple categories and assigns them in each row
    # TODO change the coln name from Catoegory to Categories
    df_exploded = df.explode('category')
    
    # get categories
    categories = df_exploded['category'].unique()

    output = []
    for current_category in categories:
        filtered_rows = df_exploded[df_exploded['category'] == current_category]
        article_summaries = []
        for idx , row in filtered_rows.iterrows():
            article_summary = summarize_article_in_chunks(row.Text)
            #TODO: nice to haves
            # df_exploded.at[idx, 'Article Summary'] = article_summary
            formatted_summary = f"APA Citation: {row.citation}\n\n Summary: {article_summary}\n\n --- "
            article_summaries.append(formatted_summary)     
        text_to_summarize = "\n\n".join(article_summaries)

        result = ScopingReview_config.SUMMARIZE_CHAT.invoke(ScopingReview_prompts.category_summary_chat_prompt.format_prompt(
            question=user_question,
            category=current_category,
            content=text_to_summarize
            ).to_messages())
   
        output.append(
            "# " + str(current_category) + "\n\n" + result.content + "\n\n" + "\n\n".join(filtered_rows.citation)
            )
    return "\n\n".join(output)

# TODO: find better place for this. Used by write_first_draft()
def extract_apa_citations(markdown_text):
    # Split the document into paragraphs
    paragraphs = markdown_text.split("\n\n")

    # Filter paragraphs that contain "PMID"
    citations = [para for para in paragraphs if "PMID" in para]
    non_citations = [para for para in paragraphs if "PMID" not in para]

    return citations, non_citations

def write_first_draft(summaries_markdown, user_question):
    citations, non_citations = extract_apa_citations(summaries_markdown)
    
    introduction_result = ScopingReview_config.SUMMARIZE_CHAT.invoke(
        ScopingReview_prompts.draft_introduction_prompt.format_prompt(
            question=user_question,
            summaries="\n\n".join(non_citations)
        ).to_messages()
    )
    
    conclusion_result = ScopingReview_config.SUMMARIZE_CHAT.invoke(
        ScopingReview_prompts.draft_conclusion_prompt.format_prompt(
            question=user_question,
            summaries="\n\n".join(non_citations),
            introduction=introduction_result.content   
        ).to_messages()
    )

    abstract_result = ScopingReview_config.SUMMARIZE_CHAT.invoke(
        ScopingReview_prompts.draft_abstract_prompt.format_prompt(
            question=user_question,
            summaries="\n\n".join(non_citations),
            introduction=introduction_result.content,
            methodology=ScopingReview_boilerplate.METHODOLOGY,
            conclusion=conclusion_result.content
        ).to_messages()
    )
    
    assembled_draft = (
        abstract_result.content + "\n\n" +
        introduction_result.content + "\n\n" + 
        ScopingReview_boilerplate.METHODOLOGY + "\n\n" + 
        "# Results/Discussion \n\n" +
        "\n\n".join(non_citations) + "\n\n" +
        conclusion_result.content + "\n\n" + 
        "# References \n\n" + "\n\n".join(citations)
    )
    
    return assembled_draft

    
def generate_keywords(df, research_question):
    relevant_rows = review_data.get_relevant_rows(df)
    all_keywords = []
    for keywords in relevant_rows['keywords']:
        keywords_list = [keyword.strip().lower() for keyword in keywords.split(',')]
        clean_keywords_list = review_data.clean_keywords(keywords_list)
        all_keywords.append(clean_keywords_list)
    
    all_titles = []   
    for title in relevant_rows['title']:
        titles_list = review_data.clean_title(title)
        all_titles.append(titles_list)
        
    formatted_prompt = ScopingReview_prompts.keyword_chat_prompt.format_prompt(
        question=research_question,
        titles=all_titles,
        keywords_list=all_keywords
    )
    result = ScopingReview_config.SUMMARIZE_CHAT.invoke(formatted_prompt.to_messages())


    print("Result - ", result)
    return result.content
