from langchain.vectorstores import FAISS

import ScopingReview.prompts as scoping_review_prompts
import ScopingReview_config.config as config

def search_scoping_review_vectorstore(
    query: str,
    embeddings= config.EMBEDDINGS,
    store= config.MPOG_VECTORSTORE):
    """
    This function searches for relevant documents in a vectorstore using a query.
    
    Args:
      query: The search query that you want to use to retrieve relevant documents from the vectorstore.
      embeddings: The embeddings parameter is a variable that contains the path to the file that stores
    the pre-trained word embeddings. These embeddings are used to represent words as vectors in a
    high-dimensional space.
      store: The `store` parameter is a path to the directory where the vector store is saved. This
    vector store contains pre-computed embeddings for a set of documents.
    
    Returns:
      a list of relevant documents based on the input query, using a vectorstore and embeddings
    specified in the configuration.
    """
    # Load vectorstore
    vectordb = FAISS.load_local(store, embeddings)
    docsearch = vectordb.as_retriever()
    docs = docsearch.get_relevant_documents(query)
    return docs

def get_scoping_review_response(
    query: str, 
    docs,
    chat=scoping_review_config.CHAT,
    chat_prompt=scoping_review_prompts.mpog_chat_prompt):
    """
    This function takes a query and a list of documents, prompts the user for a response using a
    chatbot, and returns the response.
    
    Args:
      query: The user's query or question that they want the model to respond to.
      docs: The `docs` parameter is a context or a list of documents that the model will use to generate
    a response to the given query. It can be any relevant information that the model can use to
    understand the context of the query and provide a more accurate response.
      chat: The chatbot model that will generate a response to the given query and context.
      chat_prompt: `chat_prompt` is a string that contains a placeholder for the context and question.
    It is used to prompt the user for a response in a chatbot conversation. The `format_prompt` method
    replaces the placeholders with the actual context and question before sending the prompt to the
    user.
    
    Returns:
      The function `get_model_response` takes in a query and a list of documents, and uses a chatbot
    model to generate a response to the query based on the context of the documents. The function
    returns the response generated by the chatbot model.
    """
    response = chat(chat_prompt.format_prompt(context=docs, 
                                              question=query).to_messages()
                    )
    return response